### ISSUE TITLE
TypeError: Network request failed

### ISSUE THREAD

**Issue by andrejm7** [react-keycloak/react-native-keycloak#14]
good night,

I know that is not the focus .. but I have this problem when I make 1 request after login ...

what could be going wrong?

thank you

![image](https://user-images.githubusercontent.com/13546247/94752600-13df1f00-0362-11eb-98b2-77b470d56161.png)

`const lista = () => {

    const [isLoading, setLoading] = useState(true);
    const [data, setData] = useState([]);
  
    useEffect(() => {
      fetch('GET', 'http://192.168.0.102:8082/agendas/ativas', {
        'Content-Type': 'application/json',
      })
        .then((response) => response.json())
        .then((json) => setData(json.agendas))
        .catch((error) => console.error(error))
        .finally(() => setLoading(false));
    }, []);
  
    return (
      <View style={{ flex: 1, padding: 24 }}>
        {isLoading ? <ActivityIndicator/> : (
          <FlatList
            data={data}
            keyExtractor={({ id }, index) => id}
            renderItem={({ item }) => (
              <Text>{item.nome}, {item.cor}</Text>
            )}
          />
        )}
      </View>
    );
  };
export default lista`

**Comment by andrejm7** [comment]
of so much tinkering now I'm with the error Request failed with status code 400

**Comment by panz3r** [comment]
Hi @andrejm7 ,

Thanks for reaching out to us but unfortunately we cannot help you with this issue since it is not related to the `react-native-keycloak` project in any way.

if you need help learning React and React Native you'd be better off taking a course on [Udemy](https://www.udemy.com) (and I'd suggest you this one [The Complete React Native + Hooks Course [2020 Edition]](https://www.udemy.com/course/the-complete-react-native-and-redux-course/)) or looking at some sample apps from this curated list [React-Native-Apps](https://github.com/ReactNativeNews/React-Native-Apps).

Thanks again, hope this helps you.
